spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/coupon_system
    username: root
    password: local59!
kafka:
  bootstrap-servers: localhost:9092
  topic:
    coupon-create: coupon-create
redis:
  key:
    coupon-count: coupon_count
    applied-user: applied_user
